# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- none # Triggered via Branch Policy

pool:
  vmImage: 'macos-13'

variables:
- group: e14876@exelonds.com
- group: Keysigning Keys
- group: Fastlane

steps:
# Persist git credentials
- checkout: self
  persistCredentials: true
  clean: true

# Install Enterprise Distribution Certificate
- task: InstallAppleCertificate@2
  displayName: '🔐 Install iOS Enterprise Distribution Certificates'
  inputs:
    certSecureFile: 'Exelon iOS Enterprise Distribution - Expires Feb 2024-01-05.p12'
    certPwd: '$(exelon.iOSExelonEnterpriseDistributionP12)'
    setUpPartitionIdACLForPrivateKey: false
    keychain: 'temp'

# Install all Beta Provisioning Profiles
- task: InstallAppleProvisioningProfile@1
  displayName: 'Install Profile - ACE Beta'
  inputs:
    provisioningProfileLocation: 'secureFiles'
    provProfileSecureFile: 'ACE_Staging_Enterprise_Dist_Expires_2022-01-05.mobileprovision'
  condition: contains(variables['exelon.opco'], 'ACE')

- task: InstallAppleProvisioningProfile@1
  displayName: 'Install Profile - ACE Beta WatchKit App'
  inputs:
    provisioningProfileLocation: 'secureFiles'
    provProfileSecureFile: 'ACE_Staging_Watchkit_App_Enterprise_Dist_Expires_2022-01-05.mobileprovision'
  condition: contains(variables['exelon.opco'], 'ACE')

- task: InstallAppleProvisioningProfile@1
  displayName: 'Install Profile - BGE Beta'
  inputs:
    provisioningProfileLocation: 'secureFiles'
    provProfileSecureFile: 'BGE_Staging_Enterprise_Dist_Expires_2022-01-05.mobileprovision'
  condition: contains(variables['exelon.opco'], 'BGE')

- task: InstallAppleProvisioningProfile@1
  displayName: 'Install Profile - BGE Beta WatchKit App'
  inputs:
    provisioningProfileLocation: 'secureFiles'
    provProfileSecureFile: 'BGE_Staging_Watchkit_App_Enterprise_Dist_Expires_2022-01-05.mobileprovision'
  condition: contains(variables['exelon.opco'], 'BGE')

steps:
- task: InstallAppleProvisioningProfile@1
  displayName: 'Install Profile - ComEd Beta'
  inputs:
    provisioningProfileLocation: 'secureFiles'
    provProfileSecureFile: 'ComEd_Staging_Enterprise_Dist_Expires_2022-01-05.mobileprovision'
  condition: contains(variables['exelon.opco'], 'ComEd')

- task: InstallAppleProvisioningProfile@1
  displayName: 'Install Profile - ComEd Beta WatchKit App'
  inputs:
    provisioningProfileLocation: 'secureFiles'
    provProfileSecureFile: 'ComEd_Staging_WatchKit_App_Expires_2022-01-05.mobileprovision'
  condition: contains(variables['exelon.opco'], 'ComEd')

- task: InstallAppleProvisioningProfile@1
  displayName: 'Install Profile - Delmarva Beta'
  inputs:
    provisioningProfileLocation: 'secureFiles'
    provProfileSecureFile: 'Delmarva_Staging_Enterprise_Dist_Expires_2022-01-05.mobileprovision'
  condition: contains(variables['exelon.opco'], 'Delmarva')

- task: InstallAppleProvisioningProfile@1
  displayName: 'Install Profile - Delmarva Beta WatchKit App'
  inputs:
    provisioningProfileLocation: 'secureFiles'
    provProfileSecureFile: 'Delmarva_Staging_Watchkit_App_Enterprise_Dist_Expires_2022-01-05.mobileprovision'
  condition: contains(variables['exelon.opco'], 'Delmarva')

- task: InstallAppleProvisioningProfile@1
  displayName: 'Install Profile - PECO Beta'
  inputs:
    provisioningProfileLocation: 'secureFiles'
    provProfileSecureFile: 'PECO_Staging_Enterprise_Dist_Expires_2022-01-05.mobileprovision'
  condition: contains(variables['exelon.opco'], 'PECO')

- task: InstallAppleProvisioningProfile@1
  displayName: 'Install Profile - PECO Beta WatchKit App'
  inputs:
    provisioningProfileLocation: 'secureFiles'
    provProfileSecureFile: 'PECO_Staging_Watchkit_App_Enterprise_Dist_Expires_2022-01-05.mobileprovision'
  condition: contains(variables['exelon.opco'], 'PECO')

- task: InstallAppleProvisioningProfile@1
  displayName: 'Install Profile - Pepco Beta'
  inputs:
    provisioningProfileLocation: 'secureFiles'
    provProfileSecureFile: 'Pepco_Staging_Enterprise_Dist.mobileprovision'
  condition: contains(variables['exelon.opco'], 'Pepco')

- task: InstallAppleProvisioningProfile@1
  displayName: 'Install Profile - Pepco Beta WatchKit App'
  inputs:
    provisioningProfileLocation: 'secureFiles'
    provProfileSecureFile: 'Pepco_Staging_Watchkit_App_Enterprise_Dist.mobileprovision'
  condition: contains(variables['exelon.opco'], 'Pepco')

# Install Bundler

# Install Xcodes

# Install Github SSH Key

# Install ADO SSH Key


# Build Number Bump
- task: CmdLine@2
  displayName: '⬆️ Build Number Bump'
  inputs:
    script: |
      git config --global user.email "azurePipeline@noreply.com"
      git config --global user.name "Azure Pipeline"
      git checkout -b main
      bash increment_build_number.sh
      git add Config.xcconfig
      git commit -m "Build Number Bump - Pipeline [skip ci]"
      git push --set-upstream origin main
    workingDirectory: 'tools'

# Load SPM Cache

# Build App and generate IPA
- task: CmdLine@2
  displayName: '🛠️ Build App'
  inputs:
    script: 'bundle exec fastlane build_app configuration:$(exelon.opco)-$(exelon.buildType) scheme:$(exelon.opco)-$(exelon.buildType) output_directory:$(system.defaultworkingdirectory)/archive'

# Copy files to publish? is this step even needed?

# Publish artifacts? is this step even needed?

# Generate Release Notes

#Your build pipeline references an undefined variable named ‘exelon.overrideReleaseNotes’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972

steps:
- task: richardfennellBM.BM-VSTS-XplatGenerateReleaseNotes.XplatGenerate-Release-Notes.XplatGenerateReleaseNotes@3
  displayName: '📝 Generate Release Notes based on Release Comparison API'
  inputs:
    outputfile: fastlane/ReleaseNotes.md
    templateLocation: InLine
    inlinetemplate: |
     $(exelon.overrideReleaseNotes)
     
     {{#forEach pullRequests}}
     # [{{this.pullRequestId}}]({{replace (replace this.url "_apis/git/repositories" "_git") "pullRequests" "pullRequest"}}) {{this.title}}
     
     ----
     
     * Associated Work Items
     {{#forEach this.associatedWorkitems}}
        {{#with (lookup_a_work_item ../../relatedWorkItems this.url)}}
         - [{{this.id}}]({{replace this.url "_apis/wit/workItems" "_workitems/edit"}}) - {{lookup this.fields 'System.Title'}} 
        {{/with}}
     {{/forEach}}
     * Associated Commits (this includes commits on the PR source branch not associated directly with the build)
     {{#forEach this.associatedCommits}}
         - [{{this.commitId}}]({{this.remoteUrl}}) -  {{this.comment}}
     {{/forEach}}
     {{/forEach}}

# Upload IPA & dysm files to App Center
- task: CmdLine@2
  displayName: '📤 App Center Upload'
  inputs:
    script: 'bundle exec fastlane app_center_upload app_center_api_token:$(exelon.appCenterAPIToken) app_name:EU-Mobile-App-iOS-$(exelon.opco)-$(exelon.buildType) file_path:$(system.defaultworkingdirectory)/archive/Mobile.ipa destinations:"$(exelon.distributionGroups)" dsym:$(system.defaultworkingdirectory)/archive/Mobile.app.dSYM.zip --verbose'
    