trigger:
- none # Triggered via Branch Policy

strategy:
  matrix:
    ACE:
      opco: ACE
    # BGE:
    #   opco: BGE
    # ComEd:
    #   opco: ComEd
    # DPL:
    #   opco: Delmarva
    # PECO:
    #   opco: PECO
    # Pepco:
    #   opco: Pepco


pool:
  vmImage: 'macos-13'

variables:
- group: e14876@exelonds.com
- group: Keysigning Keys
- group: Fastlane

steps:
# Persist git credentials
- checkout: self
  persistCredentials: true
  clean: true
  fetchDepth: 0

# Install Enterprise Distribution Certificate
- task: InstallAppleCertificate@2
  displayName: '🔐 Install iOS Enterprise Distribution Certificates'
  inputs:
    certSecureFile: 'Exelon iOS Enterprise Distribution - Expires Feb 2024-01-05.p12'
    certPwd: '$(iOSExelonEnterpriseDistributionP12)'
    setUpPartitionIdACLForPrivateKey: false
    keychain: 'temp'

# Install all Beta Provisioning Profiles
- task: InstallAppleProvisioningProfile@1
  displayName: 'Install Profile - ACE Beta'
  inputs:
    provisioningProfileLocation: 'secureFiles'
    provProfileSecureFile: 'ACE_Staging_Enterprise_Dist_Expires_2022-01-05.mobileprovision'
  condition: contains(variables['opco'], 'ACE')

- task: InstallAppleProvisioningProfile@1
  displayName: 'Install Profile - ACE Beta WatchKit App'
  inputs:
    provisioningProfileLocation: 'secureFiles'
    provProfileSecureFile: 'ACE_Staging_Watchkit_App_Enterprise_Dist_Expires_2022-01-05.mobileprovision'
  condition: contains(variables['opco'], 'ACE')

- task: InstallAppleProvisioningProfile@1
  displayName: 'Install Profile - BGE Beta'
  inputs:
    provisioningProfileLocation: 'secureFiles'
    provProfileSecureFile: 'BGE_Staging_Enterprise_Dist_Expires_2022-01-05.mobileprovision'
  condition: contains(variables['opco'], 'BGE')

- task: InstallAppleProvisioningProfile@1
  displayName: 'Install Profile - BGE Beta WatchKit App'
  inputs:
    provisioningProfileLocation: 'secureFiles'
    provProfileSecureFile: 'BGE_Staging_Watchkit_App_Enterprise_Dist_Expires_2022-01-05.mobileprovision'
  condition: contains(variables['opco'], 'BGE')

- task: InstallAppleProvisioningProfile@1
  displayName: 'Install Profile - ComEd Beta'
  inputs:
    provisioningProfileLocation: 'secureFiles'
    provProfileSecureFile: 'ComEd_Staging_Enterprise_Dist_Expires_2022-01-05.mobileprovision'
  condition: contains(variables['opco'], 'ComEd')

- task: InstallAppleProvisioningProfile@1
  displayName: 'Install Profile - ComEd Beta WatchKit App'
  inputs:
    provisioningProfileLocation: 'secureFiles'
    provProfileSecureFile: 'ComEd_Staging_WatchKit_App_Expires_2022-01-05.mobileprovision'
  condition: contains(variables['opco'], 'ComEd')

- task: InstallAppleProvisioningProfile@1
  displayName: 'Install Profile - Delmarva Beta'
  inputs:
    provisioningProfileLocation: 'secureFiles'
    provProfileSecureFile: 'Delmarva_Staging_Enterprise_Dist_Expires_2022-01-05.mobileprovision'
  condition: contains(variables['opco'], 'Delmarva')

- task: InstallAppleProvisioningProfile@1
  displayName: 'Install Profile - Delmarva Beta WatchKit App'
  inputs:
    provisioningProfileLocation: 'secureFiles'
    provProfileSecureFile: 'Delmarva_Staging_Watchkit_App_Enterprise_Dist_Expires_2022-01-05.mobileprovision'
  condition: contains(variables['opco'], 'Delmarva')

- task: InstallAppleProvisioningProfile@1
  displayName: 'Install Profile - PECO Beta'
  inputs:
    provisioningProfileLocation: 'secureFiles'
    provProfileSecureFile: 'PECO_Staging_Enterprise_Dist_Expires_2022-01-05.mobileprovision'
  condition: contains(variables['opco'], 'PECO')

- task: InstallAppleProvisioningProfile@1
  displayName: 'Install Profile - PECO Beta WatchKit App'
  inputs:
    provisioningProfileLocation: 'secureFiles'
    provProfileSecureFile: 'PECO_Staging_Watchkit_App_Enterprise_Dist_Expires_2022-01-05.mobileprovision'
  condition: contains(variables['opco'], 'PECO')

- task: InstallAppleProvisioningProfile@1
  displayName: 'Install Profile - Pepco Beta'
  inputs:
    provisioningProfileLocation: 'secureFiles'
    provProfileSecureFile: 'Pepco_Staging_Enterprise_Dist.mobileprovision'
  condition: contains(variables['opco'], 'Pepco')

- task: InstallAppleProvisioningProfile@1
  displayName: 'Install Profile - Pepco Beta WatchKit App'
  inputs:
    provisioningProfileLocation: 'secureFiles'
    provProfileSecureFile: 'Pepco_Staging_Watchkit_App_Enterprise_Dist.mobileprovision'
  condition: contains(variables['opco'], 'Pepco')

# Install Bundler
- task: CmdLine@2
  displayName: '⚙️ Install Bundler'
  inputs:
    script: |
      bundle update
      sudo bundle install --retry=3 --jobs=4

# Install Xcodes
- task: CmdLine@2
  displayName: '⚙️ Install Xcodes'
  inputs:
    script: |
      brew install xcodesorg/made/xcodes

# Install Github SSH Key
- task: InstallSSHKey@0
  displayName: '🔑 Install GitHub SSH key'
  inputs:
    knownHostsEntry: |
     ssh.dev.azure.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC7Hr1oTWqNqOlzGJOfGJ4NakVyIzf1rXYd4d7wo6jBlkLvCA4odBlL0mDUyZ0/QUfTTqeu+tm22gOsv+VrVTMk6vwRU75gY/y9ut5Mb3bR5BV58dKXyq9A9UeB5Cakehn5Zgm6x1mKoVyf+FFn26iYqXJRgzIZZcZ5V6hrE0Qg39kZm4az48o0AUbf6Sp4SLdvnuMa2sVNwHBboS7EJkm57XQPVU3/QpyNLHbWDdzwtrlS+ez30S3AdYhLKEOxAG8weOnyrtLJAUen9mTkol8oII1edf7mWWbWVf0nBmly21+nZcmCTISQBtdcyPaEno7fFQMDD26/s0lfKob4Kw8H
     github.com,140.82.113.4 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg=
     github.com,140.82.113.4 ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCj7ndNxQowgcQnjshcLrqPEiiphnt+VTTvDP6mHBL9j1aNUkY4Ue1gvwnGLVlOhGeYrnZaMgRK6+PKCUXaDbC7qtbW8gIkhL7aGCsOr/C56SJMy/BCZfxd1nWzAOxSDPgVsmerOBYfNqltV9/hWCqBywINIR+5dIg6JTJ72pcEpEjcYgXkE2YEFXV1JHnsKgbLWNlhScqb2UmyRkQyytRLtL+38TGxkxCflmO+5Z8CSSNY7GidjMIZ7Q4zMjA2n1nGrlTDkzwDCsw+wqFPGQA179cnfGWOWRVruj16z6XyvxvjJwbz0wQZ75XK5tKSb7FNyeIEs4TT4jk+S4dhPeAUC5y+bDYirYgM4GC7uEnztnZyaVWQ7B381AK4Qdrwt51ZqExKbQpTUNn+EjqoTwvqNj4kqx5QUCI0ThS/YkOxJCXmPUWZbhjpCg56i+2aB6CmK2JGhn57K5mj0MNdBXA4/WnwH6XoPWJzK5Nyu2zB3nAZp+S5hpQs+p1vN1/wsjk=
     github.com,140.82.113.4 ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl
     140.82.113.4 ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl
     140.82.113.4 ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCj7ndNxQowgcQnjshcLrqPEiiphnt+VTTvDP6mHBL9j1aNUkY4Ue1gvwnGLVlOhGeYrnZaMgRK6+PKCUXaDbC7qtbW8gIkhL7aGCsOr/C56SJMy/BCZfxd1nWzAOxSDPgVsmerOBYfNqltV9/hWCqBywINIR+5dIg6JTJ72pcEpEjcYgXkE2YEFXV1JHnsKgbLWNlhScqb2UmyRkQyytRLtL+38TGxkxCflmO+5Z8CSSNY7GidjMIZ7Q4zMjA2n1nGrlTDkzwDCsw+wqFPGQA179cnfGWOWRVruj16z6XyvxvjJwbz0wQZ75XK5tKSb7FNyeIEs4TT4jk+S4dhPeAUC5y+bDYirYgM4GC7uEnztnZyaVWQ7B381AK4Qdrwt51ZqExKbQpTUNn+EjqoTwvqNj4kqx5QUCI0ThS/YkOxJCXmPUWZbhjpCg56i+2aB6CmK2JGhn57K5mj0MNdBXA4/WnwH6XoPWJzK5Nyu2zB3nAZp+S5hpQs+p1vN1/wsjk=
     140.82.113.4 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg=
     
    sshPublicKey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDIQf41Kmv2JlKJRlUZSwrOrIiYqlo0ysWr8CUYWqh/dhUUr4APyNAwGFflkwBAGCyD6VAoy7+C7Licw2dUKhHrovr9F9v5voBTW8KlTIYP07rWno0B9KpwNrVsOBNMt7poFJy39K+mjiJW37uCR7w3p6YolwgSxKiGoKmftF7rif4O6msTUnZN8UpTRcaAtnO/CjrlKKw1dkIfuYjjhcz/pTIMZ7Xb7L/sHcD3Ebdg7WfA26HEkd8hw04DI+AEGhsjMdyzF9UVNc3qi0wXYlI9Obdrz8RKwHEYtolOuuL+VAVSNwyRSa4BQRDNr6klXMg9BIWWJ/zyKgBpWfdehlUPu8H8onoYQjqDFHQkmstOYGW+Dpn9K+tvIRqyCAP0QH+rDxVqKYz2xi5fnlS9Rm2ER9sNKYGdXw4J5HuPWfaXdLp+/KOQQa96+4BcPShStODUzY58t5ua1RAueAigScRH+j9ENIyVzj7zcmhDseoBGEydHdBcXlFTylw5hXCKnEU= e114805@C02ZJBB0MD6N '
    sshKeySecureFile: 'id_rsa'

# Install ADO SSH Key
- task: InstallSSHKey@0
  displayName: '🔑 Install ADO SSH key'
  inputs:
    knownHostsEntry: |
     ssh.dev.azure.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC7Hr1oTWqNqOlzGJOfGJ4NakVyIzf1rXYd4d7wo6jBlkLvCA4odBlL0mDUyZ0/QUfTTqeu+tm22gOsv+VrVTMk6vwRU75gY/y9ut5Mb3bR5BV58dKXyq9A9UeB5Cakehn5Zgm6x1mKoVyf+FFn26iYqXJRgzIZZcZ5V6hrE0Qg39kZm4az48o0AUbf6Sp4SLdvnuMa2sVNwHBboS7EJkm57XQPVU3/QpyNLHbWDdzwtrlS+ez30S3AdYhLKEOxAG8weOnyrtLJAUen9mTkol8oII1edf7mWWbWVf0nBmly21+nZcmCTISQBtdcyPaEno7fFQMDD26/s0lfKob4Kw8H
     github.com,140.82.113.4 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg=
     github.com,140.82.113.4 ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCj7ndNxQowgcQnjshcLrqPEiiphnt+VTTvDP6mHBL9j1aNUkY4Ue1gvwnGLVlOhGeYrnZaMgRK6+PKCUXaDbC7qtbW8gIkhL7aGCsOr/C56SJMy/BCZfxd1nWzAOxSDPgVsmerOBYfNqltV9/hWCqBywINIR+5dIg6JTJ72pcEpEjcYgXkE2YEFXV1JHnsKgbLWNlhScqb2UmyRkQyytRLtL+38TGxkxCflmO+5Z8CSSNY7GidjMIZ7Q4zMjA2n1nGrlTDkzwDCsw+wqFPGQA179cnfGWOWRVruj16z6XyvxvjJwbz0wQZ75XK5tKSb7FNyeIEs4TT4jk+S4dhPeAUC5y+bDYirYgM4GC7uEnztnZyaVWQ7B381AK4Qdrwt51ZqExKbQpTUNn+EjqoTwvqNj4kqx5QUCI0ThS/YkOxJCXmPUWZbhjpCg56i+2aB6CmK2JGhn57K5mj0MNdBXA4/WnwH6XoPWJzK5Nyu2zB3nAZp+S5hpQs+p1vN1/wsjk=
     github.com,140.82.113.4 ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl
     
    sshPublicKey: 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKrqa/xQQM3BrscbZZ3CrDoC/poU1Iu1HzwgAzuaf4wX “joeph.erlandson@exeloncorp.com” '
    sshKeySecureFile: 'id_ed25519'

# Build Number Bump
- task: CmdLine@2
  displayName: '⬆️ Build Number Bump'
  inputs:
    script: |
      git config --global user.email "azurePipeline@noreply.com"
      git config --global user.name "Azure Pipeline"
      git checkout -b main
      bash increment_build_number.sh
      git add Version.xcconfig
      git commit -m "Build Number Bump - Pipeline [skip ci]"
      git push -f origin main
    workingDirectory: 'tools'
  condition: contains(variables['opco'], 'ACE') # Workaround to only trigger once per PR instead of 6 times

# Load SPM Cache
- task: Cache@2
  displayName: '💾 Load SPM Cache'
  inputs:
    key: '"spm 2" | "$(Agent.OS)" | Mobile.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved'
    path: SourcePackages
    restoreKeys: 'spm | "$(Agent.OS)"'

# Build App and generate IPA
- task: CmdLine@2
  displayName: '🛠️ Build App'
  inputs:
    script: 'bundle exec fastlane build configuration:$(opco)-$(exelon.buildType) scheme:$(opco)-$(exelon.buildType) output_directory:$(system.defaultworkingdirectory)/archive'

# Generate Release Notes
- task: XplatGenerateReleaseNotes@4
  displayName: '📝 Generate Release Notes based on Release Comparison API'
  inputs:
    outputfile: 'fastlane/ReleaseNotes.md'
    templateLocation: 'File'
    templatefile: 'ci_scripts/release_notes_template'
    dumpPayloadToConsole: false
    dumpPayloadToFile: false
    replaceFile: True
    getParentsAndChildren: False
    getAllParents: False
    getIndirectPullRequests: False
    stopOnError: False
    considerPartiallySuccessfulReleases: False
    checkForManuallyLinkedWI: False
    wiqlFromTarget: 'WorkItems'

# Upload IPA & dysm files to App Center
- task: CmdLine@2
  displayName: '📤 App Center Upload'
  inputs:
    script: 'bundle exec fastlane app_center_upload app_center_api_token:$(appCenterAPIToken) app_name:EU-Mobile-App-iOS-$(opco)-$(exelon.buildType) file_path:$(system.defaultworkingdirectory)/archive/Mobile.ipa destinations:"$(exelon.distributionGroups)" dsym:$(system.defaultworkingdirectory)/archive/Mobile.app.dSYM.zip --verbose'
    
