# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

skip_docs # skip autogenerating the README.md, we are manually writing it

default_platform(:ios)
  desc "Generate new screenshots, or upload a pre-built IPA to the App Store"
platform :ios do

  lane :screenshots do
    capture_screenshots(
      app_identifier: ENV["APP_IDENTIFIER"],
      workspace: "Mobile.xcworkspace",
      scheme: ENV["SCREENSHOT_SCHEME"],
      output_directory: ENV["SCREENSHOTS_PATH"]
    )
  end

  platform :ios do |options|
    lane :uploadBuild do
      update_fastlane

      deliver(
      #   api_key_path: options[:api_key_path],
        app_identifier: options[:bundle_id],
        ipa: options[:ipa_path],
        team_id: "YU7Y757VB5",
        submit_for_review: false,
        skip_screenshots: true,
        skip_metadata: true,
        skip_app_version_update: true,
        run_precheck_before_submit: false,
        precheck_include_in_app_purchases: false,
        force: true
      )

    end
  end

platform :ios do
  desc "Refresh DSYMS"

	lane :refresh_dsyms do
    # Download dSYM files from iTC
		download_dsyms(
      version: "latest",
      username: "e20600@exelonds.com",
      team_name: "EXELON BUSINESS SERVICES COMPANY, LLC",
      app_identifier: ENV["APP_IDENTIFIER"],
      output_directory: "./fastlane/downloaded_dSYMs"
    )
		unzip(
      file: Actions.lane_context[SharedValues::DSYM_PATHS][0],
      destination_path: "./fastlane/downloaded_dSYMs/mobile.app.dSYM.zip"
    )
		appcenter_upload(
			api_token: ENV["TEST_APPCENTER_API_TOKEN"],
			owner_name: "Exelon-Digital-Projects",
			app_name: ENV["APPCENTER_APP_NAME"],
			upload_dsym_only: true,
			dsym: "./fastlane/downloaded_dSYMs/" + ENV["APP_IDENTIFIER"] + ".dSYM"
		)

		clean_build_artifacts
	end
end
