# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
devices([
  "iPhone 8 Plus",
  # "iPhone XS Max",
  # "iPad Pro (12.9-inch)"
  ])

languages([
  "en-US"
])

# The name of the scheme which contains the UI Tests
scheme(ENV["SCREENSHOT_SCHEME"])

# Where is your project (or workspace)? Provide the full path here
workspace './Mobile.xcworkspace'

# Where should the resulting screenshots be stored?
# output_directory("./fastlane/screenshots")

# remove the '#' to clear all previously generated screenshots before creating new ones
clear_previous_screenshots(true)

ios_version '13.0'

# Arguments to pass to the app on launch. See https://docs.fastlane.tools/actions/snapshot/#launch-arguments
# launch_arguments(["-favColor red"])

# For more information about all available options run
# fastlane action snapshot
